### ISSUE TITLE
Integrating razorpay payment templates in backend

### ISSUE THREAD

**Issue by tusharrao198** [tusharrao198/xpecto#4]
integrating the payment pages. 
When a user is about to register for an event, then he should be directed to payment option.

Create a dummy event template and provide register and payment hrefs in them

**Comment by ashu3103** [comment]
@tusharrao198 plz assign this issue to me

**Comment by ashu3103** [comment]
Sir, I am a bit confused about the procedure followed during payment kindly explain it to me in more detail

**Comment by tusharrao198** [comment]
Done.
