### ISSUE TITLE
Add Fest Logo in the header.

### ISSUE THREAD

**Issue by tusharrao198** [tusharrao198/xpecto#43]
Add Fest Logo in the header top-left side with Xpecto '22

![image](https://user-images.githubusercontent.com/56690827/163944243-0713de6a-826b-4f0f-9281-8ea51a7be982.png)

For eg. 
<image> | Xpecto '22

Image should be responsive in mobile view.
redirect to homepage on click image or text in header.

**Comment by palaksharma12** [comment]
I will add this
