### ISSUE TITLE
Enhancing payment pages UI

### ISSUE THREAD

**Issue by tusharrao198** [tusharrao198/xpecto#5]

**Comment by AndreTh0mas** [comment]
Commenting @Harsh

**Comment by Devharal** [comment]
Commentinf @devharal

**Comment by tusharrao198** [comment]
@Devharal   
Pages assgined:  [order.ejs](https://github.com/tusharrao198/xpecto/blob/main/templates/payment/order.ejs)
[checkout.ejs](https://github.com/tusharrao198/xpecto/blob/main/templates/payment/checkout.ejs)

**Comment by tusharrao198** [comment]
> Commenting @harsh

Pages Assigned: [paymentSuccess](https://github.com/tusharrao198/xpecto/blob/main/templates/payment/paymentsuccess.ejs)

**Comment by Devharal** [comment]
order.js done
